package egnyte

import (
	"context"
	"net/http"
	"net/url"
	"strconv"
	"strings"
)

// EventsService tracks activity in an Egnyte domain via a cursor-based
// event stream. The API retains up to 500,000 events or 30 days,
// whichever is smaller; poll no more often than every five minutes.
//
// API documentation: https://developers.egnyte.com/integration/cfs/api-docs/events-api
// OAuth scope: Egnyte.filesystem.
type EventsService service

// EventCursor is the starting point for polling the event stream.
type EventCursor struct {
	// LatestEventID is the most recent event id; use it as the initial
	// polling cursor.
	LatestEventID int64 `json:"latest_event_id"`
	// OldestEventID is the oldest event id still retained.
	OldestEventID int64  `json:"oldest_event_id"`
	Timestamp     string `json:"timestamp"`
}

// EventData carries the action-specific fields of an event. The set of
// populated fields depends on Event.Type: file_system events use the
// target/source fields, note events use NoteID, permission_change events
// use TargetPath and IsFolder.
type EventData struct {
	TargetPath    string `json:"target_path"`
	TargetID      string `json:"target_id"`
	TargetGroupID string `json:"target_group_id"`
	SourcePath    string `json:"source_path"`
	SourceID      string `json:"source_id"`
	SourceGroupID string `json:"source_group_id"`
	IsFolder      bool   `json:"is_folder"`
	NoteID        string `json:"note_id"`
}

// PermissionEntry is one subject/privilege pair of a permission change.
type PermissionEntry struct {
	Subject string `json:"subject"` // e.g. "/user/6"
	Priv    string `json:"priv"`    // NONE, VIEWER_ONLY, READ, READWRITE, RWD, MODIFY
}

// ChangedPermission is one ADD or DELETE within a permission change.
type ChangedPermission struct {
	Action string          `json:"action"` // ADD or DELETE
	Entry  PermissionEntry `json:"entry"`
}

// ChangePermissionEvent lists the individual permission changes.
type ChangePermissionEvent struct {
	ChangedPermissions []ChangedPermission `json:"changedPermissions"`
}

// PermissionChangeAttributes carries extra metadata present only on
// permission_change events (v2).
type PermissionChangeAttributes struct {
	ChangeGroupEvents     []map[string]any       `json:"changeGroupEvents"`
	ChangePermissionEvent *ChangePermissionEvent `json:"changePermissionEvent"`
	ChangeContext         map[string]any         `json:"changeContext"`
	TargetFolderID        string                 `json:"targetFolderId"`
	GroupChange           bool                   `json:"groupChange"`
}

// Event is one entry of the domain event stream.
type Event struct {
	ID           int64  `json:"id"`
	Timestamp    string `json:"timestamp"`
	ActionSource string `json:"action_source"` // WebUI, SyncEngine, Mobile, PublicAPI, ...
	Actor        int    `json:"actor"`         // numeric user id
	Type         string `json:"type"`          // file_system, note or permission_change
	Action       string `json:"action"`        // create, delete, restore, move, copy, permission_change
	// ObjectDetail optionally links to the affected resource's metadata
	// endpoint.
	ObjectDetail string    `json:"object_detail"`
	Data         EventData `json:"data"`
	// EventTypeSpecificAttributes is non-nil only on permission_change
	// events returned by the v2 endpoint.
	EventTypeSpecificAttributes *PermissionChangeAttributes `json:"eventTypeSpecificAttributes"`
}

// EventList is one page of the event stream. LatestID is the cursor for
// the next poll.
type EventList struct {
	LatestID int64   `json:"latest_id"`
	OldestID int64   `json:"oldest_id"`
	Count    int     `json:"count"`
	Events   []Event `json:"events"`
}

// EventListOptions filter event listings. Zero values are omitted.
type EventListOptions struct {
	// Folder scopes results to a folder and its subfolders.
	Folder string
	// Suppress hides events generated by the current application
	// ("app") or current user ("user").
	Suppress string
	// Types filters to specific event types (file_system, note,
	// permission_change); multiple types are pipe-joined.
	Types []string
	// Count caps the number of events returned (1-100, default 50).
	Count int
	// Reverse traverses events in descending order.
	Reverse bool
}

func (o *EventListOptions) values() url.Values {
	v := url.Values{}
	if o == nil {
		return v
	}
	if o.Folder != "" {
		v.Set("folder", o.Folder)
	}
	if o.Suppress != "" {
		v.Set("suppress", o.Suppress)
	}
	if len(o.Types) > 0 {
		v.Set("type", strings.Join(o.Types, "|"))
	}
	if o.Count > 0 {
		v.Set("count", strconv.Itoa(o.Count))
	}
	if o.Reverse {
		v.Set("reverse", "1")
	}
	return v
}

// Cursor returns the latest and oldest event ids. Call it once to
// establish a starting cursor before polling List.
//
// GET /pubapi/v1/events/cursor
func (s *EventsService) Cursor(ctx context.Context) (*EventCursor, *Response, error) {
	req, err := s.client.NewRequest(ctx, http.MethodGet, "v1/events/cursor", nil)
	if err != nil {
		return nil, nil, err
	}
	cursor := new(EventCursor)
	resp, err := s.client.Do(req, cursor)
	if err != nil {
		return nil, resp, err
	}
	return cursor, resp, nil
}

// List returns events after the given cursor id. v1 returns file_system
// and note events. When no new events exist the server responds 204 and
// the returned list is empty (check resp.StatusCode or len(Events)).
//
// GET /pubapi/v1/events
func (s *EventsService) List(ctx context.Context, cursorID int64, opts *EventListOptions) (*EventList, *Response, error) {
	return s.list(ctx, "v1", cursorID, opts)
}

// ListV2 is List against the v2 endpoint, which additionally returns
// permission_change events (all types by default).
//
// GET /pubapi/v2/events
func (s *EventsService) ListV2(ctx context.Context, cursorID int64, opts *EventListOptions) (*EventList, *Response, error) {
	return s.list(ctx, "v2", cursorID, opts)
}

func (s *EventsService) list(ctx context.Context, version string, cursorID int64, opts *EventListOptions) (*EventList, *Response, error) {
	q := opts.values()
	q.Set("id", strconv.FormatInt(cursorID, 10))
	req, err := s.client.NewRequest(ctx, http.MethodGet, version+"/events?"+q.Encode(), nil)
	if err != nil {
		return nil, nil, err
	}
	list := new(EventList)
	resp, err := s.client.Do(req, list)
	if err != nil {
		return nil, resp, err
	}
	return list, resp, nil
}
